export const SET_AUTH_DATA = 'SET_AUTH_DATA'
export const SET_USER_DATA = 'SET_USER_DATA'

export const SET_FORGOTTEN_EMAIL = 'SET_FORGOTTEN_EMAIL'
export const CLEAR_FORGOTTEN_EMAIL = 'CLEAR_FORGOTTEN_EMAIL'

export const SET_SEARCHING_TEXT = 'SET_SEARCHING_TEXT'
export const SET_SEARCH_BAR_TEXT = 'SET_SEARCH_BAR_TEXT'

export const ROOT_CHANGED = 'ROOT_CHANGED'
export const RECEIVE_USER = 'RECEIVE_USER'
export const LOGOUT = 'LOGOUT'
export const RECEIVE_SALONS = 'RECEIVE_SALONS'
export const RECEIVE_PACKS = 'RECEIVE_PACKS'
export const RECEIVE_REQUEST = 'RECEIVE_REQUEST'
export const RECEIVE_SETTINGS = 'RECEIVE_SETTINGS'

export const RECEIVE_FCM_TOKEN = 'RECEIVE_FCM_TOKEN'
