export const USERS = 'users'
export const USER_EMAIL = 'email'
export const USER_NAME = 'name'
export const USER_PHONE = 'tel'

export const SALONS = 'salons'
export const SALON_ADDRESS = 'address'
export const SALON_CONTACTPERSON = 'contactPerson'
export const SALON_DESCRIPTION = 'description'
export const SALON_EMAIL = 'email'
export const SALON_ID = 'id'
export const SALON_LATITUDE = 'lat'
export const SALON_LONGITUDE = 'lng'
export const SALON_NAME = 'name'
export const SALON_PHONE = 'phone'
export const SALON_SITE = 'webSite'