export default {
  WALKTHROUGH: 'Walkthrough',
  SIGN_UP: 'Sign up',
  SIGN_IN: 'Sign in',
  FORGOT_PASSWORD: 'Forgot password',
  CHANGE_PASSWORD: 'Change password',
  SALONS_MAP: 'Salons map',
  LANDING_STEP_2: 'Selection',
  REQUEST_CONFIRMATION: 'Request confirmation',
  LOADING: 'Loading',
  MENU: 'Menu',
  ACCOUNT_BUTTON: 'Account button',
  CHECKOUT: 'Checkout',
  SELECT_PACKAGE: 'Select package',
  BUY_PACKAGE: 'Buy package',
  PACKAGE_CONFIRMATION: 'Package confirmation',
  REQUESTED: 'Requested',
  REQUESTED_APPOINTMENTS: 'Requested appointments',
  SCHEDULED_APPOINTMENTS: 'Scheduled appointments',
  SCHEDULED: 'Scheduled',
  PAST_APPOINTMENTS: 'Past appointments',
  CANCELLATION_POLICY: 'Cancellation policy',
  BUY_CANCELLATION: 'Buy cancellation',
  SALON_INFO: 'Salon info',
  WAITING_LIST: 'Waiting list',
  SIMPLE_SPINNER: 'Simple spinner'
}
