# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Vurve' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks

  # Pods for Vurve

  use_frameworks!
  pod 'Firebase'
  pod 'Firebase/Messaging'
  pod 'Firebase/Crash'

  target 'VurveTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
